# Add configuration values below, rename the file to application.yml and save.

AWS_ACCESS_KEY_ID:
AWS_SECRET_ACCESS_KEY:

development:
  AWS_BUCKET:

staging:
  SENDGRID_USERNAME:
  SENDGRID_PASSWORD:
  AWS_BUCKET:

production:
  AWS_BUCKET:
  SENDGRID_USERNAME:
  SENDGRID_PASSWORD:
